# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
<<<<<<< HEAD
"POT-Creation-Date: 2021-07-29 12:39+0200\n"
=======
"POT-Creation-Date: 2022-10-21 13:01+0200\n"
>>>>>>> develop
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

<<<<<<< HEAD
#: api/serializers/entry.py:127
=======
#: api/serializers/entry.py:139
>>>>>>> develop
msgid "will not be published"
msgstr "Werden nicht veröffentlicht"

#: api/serializers/relation.py:23
msgid "Relation already exists"
msgstr "Verknüpfung existiert bereits"

#: api/serializers/relation.py:30 api/views.py:195 api/views.py:225
msgid "Current user is not the owner of this entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

<<<<<<< HEAD
#: api/views.py:191 api/views.py:776 api/views.py:805
#: media_server/serializers.py:30
=======
#: api/views.py:199 api/views.py:232 api/views.py:1048 api/views.py:1077
#: media_server/serializers.py:38
>>>>>>> develop
msgid "Entry does not exist"
msgstr "Eintrag existiert nicht"

#: api/views.py:313
msgid "Schema not found for the given query"
msgstr "Kein Schema gefunden"

#: api/views.py:354 api/views.py:1043
msgid "User does not exist"
msgstr "Benutzer existiert nicht"

<<<<<<< HEAD
#: core/models.py:143
=======
#: core/models.py:121
>>>>>>> develop
#, python-format
msgid "Type %(type_source)s does not belong to any active schema"
msgstr "Typ %(type_source)s gehört zu keinem aktiven Schema"

<<<<<<< HEAD
#: core/models.py:150
=======
#: core/models.py:128
>>>>>>> develop
#, python-format
msgid "Invalid data: %(error)s"
msgstr "Ungültige Daten: %(error)s"

<<<<<<< HEAD
#: core/models.py:153
msgid "Data without type"
msgstr "Daten ohne Typ"

#: core/models.py:189
=======
#: core/models.py:131
msgid "Data without type"
msgstr "Daten ohne Typ"

#: core/models.py:167
>>>>>>> develop
msgid "Both entries must belong to the same user"
msgstr "Beide Einträge müssen demselben Benutzer gehören"

#: core/schemas/__init__.py:26
msgid "Schemas improperly configured"
msgstr "Schemata ungenügend konfiguriert"

#: core/schemas/__init__.py:64
msgid "Active schemas contain duplicate types"
msgstr "Aktive Schemata enthalten Duplikate"

#: core/schemas/entries/exhibition.py:45 core/schemas/general.py:100
#: core/schemas/general.py:116 core/schemas/general.py:150
#: core/schemas/general.py:173 core/schemas/general.py:189
#: core/schemas/general.py:210 core/schemas/general.py:232
msgid "and"
msgstr "und"

#: core/utils.py:6
#, python-format
msgid "Enter %(label)s"
msgstr "%(label)s eintragen"

#: core/validators.py:15
#, python-format
msgid "Invalid type: %(error)s"
msgstr "Ungültiger Typ: %(error)s"

#: core/validators.py:23
msgid "Keywords contains duplicate entries"
msgstr "Schlagwörter enthalten Duplikate"

#: core/validators.py:25
#, python-format
msgid "Invalid keywords: %(error)s"
msgstr "Ungültige Schlagwörter: %(error)s"

#: core/validators.py:39
msgid "Same language is defined multiple times"
msgstr "Dieselbe Sprache wird mehrmals definiert"

#: core/validators.py:41
#, python-format
msgid "Invalid texts: %(error)s"
msgstr "Ungültige Texte: %(error)s"

<<<<<<< HEAD
#: media_server/archiver/controller/default.py:61
msgid "empty"
msgstr ""

#. Translators: Something goes wrong and the media for archival is not found.
#: media_server/archiver/messages/errors.py:4
#, fuzzy
#| msgid "Media object does not exist"
msgid "Media assets do not exist"
msgstr "Medienobjekt existiert nicht"

#. Translators: Only media assets of one entry can be archived together. 0 or more than one found
#: media_server/archiver/messages/errors.py:9
#, python-format
msgid "All media objects must belong to one entry. %(n_entries)d found"
msgstr ""

#. Translators: Something goes wrong and the user tried to archive an media asset, which he does not "own"
#: media_server/archiver/messages/errors.py:13 media_server/views.py:101
#: media_server/views.py:182 media_server/views.py:227
msgid "Current user is not the owner of this media object"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Medienobjekts"

#. Translators: The archival service is unavailable due to unknown reasons
#: media_server/archiver/messages/errors.py:18
#, python-format
msgid "%(service)s temporarily unavailable, try again later."
msgstr ""

#: media_server/archiver/messages/success.py:5
#, python-format
msgid ""
"Successfully %(modification_type)s %(object_description)s to %(service)s"
msgstr ""

#. Translators: Default message for fields with no value
#: media_server/archiver/messages/validation/__init__.py:6
msgid "Field may not be null."
msgstr ""

#. Translators: Default message for empty required fields
#: media_server/archiver/messages/validation/__init__.py:9
msgid "Missing data for required field."
msgstr ""

#. Translators: Default message for invalid type, for example a number is requested and en e-mail-address is given
#: media_server/archiver/messages/validation/__init__.py:12
#, fuzzy
#| msgid "Invalid type: %(error)s"
msgid "Invalid type."
msgstr "Ungültiger Typ: %(error)s"

#. Translators: Default message, when validation failed to unknown reason
#: media_server/archiver/messages/validation/__init__.py:15
#, fuzzy
#| msgid "Invalid license"
msgid "Invalid value."
msgstr "Ungültige Lizenz"

#. Translators: Displayed, when missing an author
#: media_server/archiver/messages/validation/thesis.py:4
msgid "An author is required"
msgstr ""

#. Translators: Displayed, when missing language
#: media_server/archiver/messages/validation/thesis.py:8
msgid "Language is required"
msgstr ""

#. Translators: Displayed, when missing Supervisor
#: media_server/archiver/messages/validation/thesis.py:11
msgid "A supervisor is required"
msgstr ""

#. Translators: Displayed, when missing an English abstract
#: media_server/archiver/messages/validation/thesis.py:14
msgid "An English Abstract is required"
msgstr ""

#. Translators: Displayed, when missing a German abstract
#: media_server/archiver/messages/validation/thesis.py:17
msgid "A German Abstract is required"
msgstr ""

#: media_server/serializers.py:33
=======
#: media_server/clamav.py:36
msgid "File is infected with malware"
msgstr "Datei ist mit Malware infiziert"

#: media_server/serializers.py:41
>>>>>>> develop
msgid "Current user is not the owner of entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

#: media_server/validators.py:17
#, python-format
msgid "Invalid license: %(error)s"
msgstr "Ungültige Lizenz: %(error)s"

#: media_server/validators.py:22
msgid "Invalid license"
msgstr "Ungültige Lizenz"

<<<<<<< HEAD
#: media_server/views.py:114 media_server/views.py:190
#: media_server/views.py:235
msgid "Media object does not exist"
msgstr "Medienobjekt existiert nicht"

#: media_server/views.py:132
msgid "No space left for user"
msgstr "Kein Speicherplatz mehr für diesen Benutzer"

#: media_server/views.py:251
msgid "Asset validation successful"
msgstr ""

=======
#: media_server/views.py:115 media_server/views.py:201
#: media_server/views.py:246
msgid "Current user is not the owner of this media object"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Medienobjekts"

#: media_server/views.py:133 media_server/views.py:209
#: media_server/views.py:254
msgid "Media object does not exist"
msgstr "Medienobjekt existiert nicht"

#: media_server/views.py:151
msgid "No space left for user"
msgstr "Kein Speicherplatz mehr für diesen Benutzer"

>>>>>>> develop
#: portfolio/settings.py:250
msgid "German"
msgstr "Deutsch"

#: portfolio/settings.py:251
msgid "English"
msgstr "Englisch"
